CREATE TABLE book
(
    BOOK_ID CHAR(40) PRIMARY KEY NOT NULL,
    BOOK_NAME VARCHAR(256) NOT NULL,
    FILE_NAME VARCHAR(256) NOT NULL,
    ORDER_NO INT(11),
    ACCESS_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FILE_LENGTH BIGINT(20) DEFAULT '0' NOT NULL,
    STATUS INT(11) DEFAULT '1' NOT NULL,
    MIME VARCHAR(64) DEFAULT '' NOT NULL,
    FILE_PATH VARCHAR(1024) DEFAULT '' NOT NULL
);